version: '3.1'

services:
  postgres:
    image: postgres:13
    container_name: shop
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop123
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
